---
title: "Epi Final"
author: "Margaret Patterson"
date: "12/13/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, message = FALSE, warning = FALSE)
```

#Packages and data import
```{r}
library(tidyverse)
library(stringr)
library(dplyr)
library(lme4)
library(broom)
library(scales)
library(readxl)
library(broom.mixed)
library(ggplot2)

mask <- read_csv("nytimes_covid_masks.csv")   
colleges <- read_csv("nytimes_covid_college_cases.csv")
recent <- read_csv("us-counties-recent.csv")  
election <- read_csv("countypres_2000-2020.csv")
calicoll <- read_excel("colleges.xlsx")
```


#Initial clean
```{r}
set.seed(416)

#county_state (for joining), matching fips, cleaning imported data
mask <- mask %>%
  mutate(fips = str_pad(COUNTYFP, 5, side = c("left"), pad = "0")) %>%
  select(fips, NEVER, ALWAYS) %>%
  rename_all(str_to_lower)

colleges <- colleges %>%
  mutate(county_state = paste(county, state, sep = ", ")) %>%
  select(state, county, city, ipeds_id, college, cases, cases_2021, county_state)

recent <- recent %>%
  mutate(county_state = paste(county, state, sep = ", "))

election <- election %>%
  mutate(fips = str_pad(county_fips, 5, side = c("left"), pad = "0")) %>%
  select(fips, candidate, party, candidatevotes, totalvotes, fips)

calicoll <- calicoll %>%
  mutate(fips = str_pad(fips, 5, side = c("left"), pad = "0")) %>%
  mutate(fips = as.character(fips))
```

#Joins
```{r}
recentcoll <- full_join(recent, colleges, by = "county_state") #recent, colleges
collrecoll <- full_join(recentcoll, election, by = "fips") #recent, colleges, election
addcali <- full_join(collrecoll, calicoll, by = "fips") #recent, colleges, election, Cali - uses excel
addmask <- full_join(addcali, mask, by = "fips")
```

#Clean new dataset
```{r}
cdf <- addmask %>%
  na.omit(college.x) %>%
  na.omit(`total enrollment`) %>%
  select(date, college.x, city.x, state.x, county.x, `county pop`, fips, cases.x, deaths, ipeds_id.x, `total enrollment`, `student vax`,
         cases.y, cases_2021, never) %>%
  rename(college = college.x) %>%
  rename(ipeds_id = ipeds_id.x) %>%
  rename(city = city.x) %>%
  rename(county = county.x) %>%
  rename(state = state.x) %>%
  rename(cas_cty = cases.x) %>%
  rename(dth_cty = deaths) %>%
  rename(cas_coll = cases.y) %>%
  rename(cas_coll_21 = cases_2021) %>%
  mutate(cs_cty_ratio = (cas_cty/`county pop`)) %>%
  mutate(dth_cty_ratio = (dth_cty/`county pop`)) %>%
  mutate(cs_collratio = (cas_coll/`total enrollment`)) %>%
  mutate(cs_coll_21_ratio = (cas_coll_21/`total enrollment`)) %>%
  group_by(college) 
cdf
```

#Finding CA colleges
```{r}
california <- cdf %>%  #75
  filter(state == "California") %>%
  nest()
```

#Filtering out large duplicates, filter to 13 with no vax info
```{r}
ncdf <- cdf %>%
  filter(ipeds_id == c("110617", "110583", "110608", "121150", "120254", "122597", "122755", 
                       "110635", "110644", "110662", "123961", "120883", "122612")) %>%
  group_by(ipeds_id) %>%
  mutate(n = n()) %>%
  select(college, ipeds_id, cas_cty, dth_cty, cas_coll, cas_coll_21, 
         `student vax`, never, cs_cty_ratio, 
         dth_cty_ratio, cs_collratio, cs_coll_21_ratio, n) %>%
  nest() %>%
  unnest()

ncdf
```

#Models, used mod3 for analysis
```{r}
#Mixed effects
mod <- ncdf %>%
  lmer(dth_cty_ratio ~ 1 + cs_collratio + `student vax` + never + cs_cty_ratio + cs_coll_21_ratio + (1 | ipeds_id), data = .)
summary(mod)

mod2 <- ncdf %>%
  lmer(dth_cty_ratio ~ 1 + `student vax` + (1 | ipeds_id), data = .)
summary(mod2)

mod3 <- ncdf %>%
  lmer(dth_cty_ratio ~ 1 + `student vax`  + never + (1 | ipeds_id), data = .)


library(lmerTest)
summary(mod3)
mod3 %>%
  tidy()
broom::augment(mod3)
anova(mod3)

```

#Facet plot
```{r}
library(broom.mixed)
mod3 %>%
  augment(data = ncdf) %>%
  ggplot(aes(x = `student vax`, color = never)) +
  geom_line(aes(y = dth_cty_ratio), linetype = 1) +
  geom_line(aes(y = .fitted), linetype = 2) +
  geom_line(aes(y = .fixed), linetype = 3) +
  labs(x = "Percent Students Vaccinated", y = "County Death Rate", title = "County Death Rate and Student Vaccinations") +
  facet_wrap(~ college, ncol = 4)
```

#Pairs plots
```{r}
library(GGally)
exposurepairs <- ncdf %>%
  select(`student vax`, dth_cty_ratio) %>%
  ggpairs()
exposurepairs

bigpairs <- ncdf %>%
  select(`student vax`, never, cs_cty_ratio, dth_cty_ratio, cs_collratio) %>%
  rename(county_cases = cs_cty_ratio, deaths = dth_cty_ratio, college_cases = cs_collratio ) %>%
  ggpairs()
bigpairs
```

#Corr plot
```{r}
library(ggcorrplot)
cormod2 <- ncdf %>%
  select(ipeds_id, dth_cty_ratio, cs_collratio, cs_coll_21_ratio, cs_cty_ratio, `student vax`, never) %>%
  mutate(dth_cty_ratio = as.numeric(dth_cty_ratio)) %>%
  mutate(ipeds_id = as.numeric(ipeds_id)) %>%
  rename(`county deaths` = dth_cty_ratio) %>%
  rename(`college cases` = cs_collratio) %>%
  rename(`college cases 2021` = cs_coll_21_ratio) %>%
  rename(`county cases` = cs_cty_ratio) %>%
  rename(`student vaccination rate` = `student vax`) %>%
  rename(`never use mask` = never) 

cplot2 <- cormod2 %>%
  cor(x = cormod2) %>%
  ggcorrplot(method = "circle", type = "lower", title = "Student Vaccination and COVID-19 Cases and Deaths")
cplot2
```

#Plot
```{r}
plt <- ncdf %>%
  select(college, `student vax`, dth_cty_ratio, never) %>%
  ggplot(aes(x = never, y = dth_cty_ratio, color = college)) +
  geom_boxplot()
plt

plt2 <- ncdf %>%
  select(college, `student vax`, dth_cty_ratio, never) %>%
  ggplot(aes(x =  `student vax`, y = dth_cty_ratio, color = college)) +
  geom_boxplot()
plt2  
```



